hellodjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^admin/', include(admin.site.urls), name="admin"),
]

polls/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
	#ex: /polls/
	url(r'^$', views.index, name='index'),
	#ex: /polls/5/
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	#ex: /polls/5/results/
	url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	#ex: /polls/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),	
	
	#beat_generator ex:rock, jazz
	url(r'^beats/(?P<beats_in_measure>[0-9]+)/$', views.beats, name='beats'),
	url(r'^beats/$', views.beat_settings, name = 'beat_settings'),
	url(r'^beats/sheet_music/$', views.sheet_music, name = 'sheet_music'),
	url(r'^beats/beat_saved/$', views.beat_saved, name = 'beat_saved'),
	url(r'^beats/beat_index/$', views.beat_index, name = 'beat_index'),
	url(r'^beats/beat_detail/(?P<beat_id>[0-9]+)/$', views.beat_detail, name = 'beat_detail'),
	url(r'^beats/delete_beat/(?P<beat_id>[0-9]+)/$', views.delete_beat, name = 'delete_beat'),
	url(r'^beats/delete_all_beats/$', views.delete_all_beats, name = 'delete_all_beats'),
	url(r'^beats/create_a_pdf/$', views.pdf_generating_view, name = 'pdf_generator'),
	url(r'^beats/beat_pdf_saved/$', views.upload_file, name = 'file_upload'),
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.forms import ModelForm

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        
class Beat(models.Model):
    beat_name = models.CharField(max_length=200)
    snare_hits = models.CharField(max_length=200, default = "empty")
    bass_kicks = models.CharField(max_length=200, default = "empty")
    creation_date = models.DateTimeField(auto_now_add = True, editable=False, null=True)
    beat_pdf = models.ImageField(upload_to = 'pic_folder/')
    pdf = models.FileField(upload_to = 'sheet_music/%Y/%m',null=True)
    class Meta:
        get_latest_by = 'creation_date'
    def __str__(self):
        return self.beat_name
    def save(self, force_insert=False, force_update=False, using=None):
        if self.beat_name == "Harry":
            self.beat_name = "Hairy Hairy Harry (Harry is Hairy!)"
        super(Beat, self).save() # Call the "real" save() method.
        
class BeatForm(ModelForm):
    class Meta:
        model = Beat
        fields = ['beat_name','snare_hits','bass_kicks']

polls/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django import template
import beat_generator
reload(beat_generator)
import sys
from django.core.urlresolvers import reverse
from django.views import generic
from django.template import RequestContext
from reportlab.pdfgen import canvas
from django.shortcuts import render_to_response
from .forms import UploadFileForm
from .uploadedFilesHandling import handle_uploaded_file


from django.shortcuts import render, get_object_or_404
from .models import Choice, Question, Beat

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
	
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
	
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
	
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
            })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a 
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
    
def beats(request, beats_in_measure):
    new_beat = beat_generator.GenerateBeat(beats_in_measure)
    new_beat.save()
    latest_beat = new_beat
    context = {'beats_in_measure': beats_in_measure, 'latest_beat':latest_beat}
    return render(request, 'polls/beats.html', context)

    
def beat_settings(request):
    return render(request, 'polls/beat_settings.html')
    
def sheet_music(request):
    pdf = open('C:\Gideon\Professional Education\djangoTutorialWithoutGal\hellodjango3\polls\static\polls\images\\testFile33.pdf', 'rb')
    response = HttpResponse(pdf.read(), content_type='application/pdf')
    response['Content-Disposition'] = 'filename=some_file.pdf'
    return response
    pdf.closed
    #return render(request, 'polls/sheet_music.html')
    
def beat_detail(request, beat_id):
    beat = get_object_or_404(Beat, pk=beat_id)
    return render(request, 'polls/beat_detail.html', {'beat':beat})
    
def beat_saved(request):
    beat_name = request.POST["beat_name"]
    beat = Beat.objects.latest()

    if beat_name == "":
        context = {'error_message': "DUDE, this beat deserves a name! You must name it before you save it.",
            'latest_beat': beat,}
        return render(request, 'polls/beats.html',context)
    else:
        beat.beat_name = beat_name
        beat.save()
        return HttpResponseRedirect(reverse('polls:beat_index'))
    

def beat_index(request):
    beat_list = Beat.objects.all()
    context = {'beat_list':beat_list}
    return render(request, 'polls/beat_index.html', context)
    
def delete_beat(request, beat_id):
    beat = Beat.objects.get(pk=beat_id)
    beat.delete()
    return HttpResponseRedirect(reverse('polls:beat_index'))
    
def delete_all_beats(request):
    Beat.objects.all().delete()
    return HttpResponseRedirect(reverse('polls:beat_index'))

def pdf_generating_view(request):
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="somefilename.pdf"'

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)
    p.rect(280,480,200,40,fill=0)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(300, 500, "Sheet music goes here.")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()
    return response
#    
#def give_beat_a_pdf(request):
#    beat_pdf = request.POST["beat_pdf"]
#    beat = Beat.objects.latest()
#    beat.beat_pdf = beat_pdf
#    
def upload_file(request):
    beat = Beat.objects.latest()
    beat.beat_pdf = request.POST["beat_file"]
    beat.save()
    return HttpResponseRedirect(reverse('polls:beat_index'))

polls/templates/common_audiofield.html
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}audiofield/page-player/css/page-player.css" />
<style type="text/css">
  ul.playlist li a {
    color: #333333;
    display: block;
    font-family: "Lucida Grande","DejaVu Sans","Bitstream Vera Sans","Verdana,Arial,sans-serif";
    font-size: 12px;
    vertical-align: top;
  }
</style>
<!-- soundManager.useFlashBlock: related CSS -->
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}audiofield/flashblock/flashblock.css" />
<script type="text/javascript" src="{{ STATIC_URL }}audiofield/script/soundmanager2.js"></script>

<script>
/* --------
  Config override: This demo uses shiny flash 9 stuff, overwriting Flash 8-based defaults
  Alternate PP_CONFIG object must be defined before soundManager.onready()/onload() fire.
  Alternately, edit the config in page-player.js to simply use the values below by default
-------- */

// demo only, but you can use these settings too..
soundManager.flashVersion = 9;
soundManager.preferFlash = true; // for visualization effects
soundManager.useHighPerformance = true; // keep flash on screen, boost performance
soundManager.wmode = 'transparent'; // transparent SWF, if possible
soundManager.useFastPolling = true; // increased JS callback frequency
soundManager.url = {{ STATIC_URL }}+'audiofield/swf/';
soundManager.debugFlash = false;
soundManager.debugMode = true;
// Added
//soundManager.useHTML5Audio = false;

// custom page player configuration

var PP_CONFIG = {
  autoStart: false,      // begin playing first sound when page loads
  playNext: false,        // stop after one sound, or play through list until end
  useThrottling: false,  // try to rate-limit potentially-expensive calls (eg. dragging position around)</span>
  usePeakData: true,     // [Flash 9 only] whether or not to show peak data (left/right channel values) - nor noticable on CPU
  useWaveformData: false,// [Flash 9 only] show raw waveform data - WARNING: LIKELY VERY CPU-HEAVY
  useEQData: false,      // [Flash 9 only] show EQ (frequency spectrum) data
  useFavIcon: false,     // try to apply peakData to address bar (Firefox + Opera) - performance note: appears to make Firefox 3 do some temporary, heavy disk access/swapping/garbage collection at first(?) - may be too heavy on CPU
  useMovieStar: true     // Flash 9.0r115+ only: Support for a subset of MPEG4 formats.
}
</script>

<script type="text/javascript" src="{{ STATIC_URL }}audiofield/page-player/script/page-player.js"></script>
<script type="text/javascript">

// demo only..
function setTheme(sTheme) {
  var o = document.getElementsByTagName('ul')[0];
  o.className = 'playlist'+(sTheme?' '+sTheme:'');
  return false;
}
</script>

polls/templates/polls/beat_detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/beats.css' %}" />
This page will display the beat corresponding to the request id.

<h1>{{beat.beat_name}}</h1>
<h2>Kick the bass drum on beats {{beat.bass_kicks}}</h2>
<h2>Hit the snare drum on beats {{beat.snare_hits}}</h2>
<h2>Beat file: {{beat.beat_pdf.name}}; {{beat.beat_pdf.url}}; {{beat.beat_pdf.path}}; </h2>

<h3><a href="{%url 'polls:delete_beat' beat.id%}">Delete the beat</a><h3>

polls/templates/polls/beat_index.html
{% if beat_list %}
	<ul>
	{% for beat in beat_list %}
		<li><a href="{% url 'polls:beat_detail' beat.id%}">{{beat}}</li>
	{%endfor%}
	</ul>
{%else%}
	<p>No beats have been saved.</p>
{%endif%}

<li><a href="{% url 'polls:beat_settings' %}">Create another beat</a></li>
<li><a href="{% url 'polls:delete_all_beats' %}">Delete all beats</a></li>

<li><a href="{% url 'polls:pdf_generator' %}">Generate a PDF</a></li>

polls/templates/polls/beat_saved.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/beats.css' %}" />

<h1> The beat has been saved. </h1>
<li><a href="{%url 'polls:beat_index'%}">View Saved Beats</a></li>

polls/templates/polls/beat_settings.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/beats.css' %}" />

<li><a href="{% url 'polls:beats' 8 %}">Generate a beat</a></li>
<li><a href="{% url 'polls:index'%}">Return to main page</a></li>

polls/templates/polls/beats.html
{% if error_message %}<p><strong>{{error_message }}</strong></p>{% endif %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/beats.css' %}" />

<ul>
<li> There are {{beats_in_measure}} beats in the measure</li>
</ul>

<ul>
<li>Kick the bass on beats: {{latest_beat.bass_kicks}}</li>
<li>Hit the snare on beats: {{latest_beat.snare_hits}}</li>
</ul>

<li> <a href="{% url 'polls:beat_settings' %}">Change beat settings</a></li>
<li><a href="{% url 'polls:sheet_music'%}">View sheet music</a></li>
<li><a href="{% url 'polls:beat_index' %}">View all saved beats</a></li>


<form action="{%url 'polls:beat_saved' %}" method="post">
{% csrf_token %}
	<input type="text" name="beat_name" id="beat_name_box" value =""/>
	<label for="beat_name_box">Enter a name for your beat.</label></br>
<input type="submit" value="Save beat"/>
</form>

<form action="{%url 'polls:file_upload' %}" method="post">
{% csrf_token %}
	<input type="file" name="beat_file" id="picture" value="Upload a file dude." accept="image/*">
<input type="submit">
</form>

polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>
{% if error_message %}<p><strong>{{error_message }}</strong></p>{% endif %}

<form action="{%url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name ="choice" id="choice{{ forloop.counter}}" value="{{choice.id}}" />
	<label for="choice{{ forloop.counter}}">{{choice.choice_text}}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
<ul><a href="{% url 'polls:index' %}">Return to Question List</a></ul>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1> Yo yo, here are some questions I've been pondering and a neat little random-drum-beat-generator</h1>
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

<ul>
<li>
<a href="{% url 'polls:beat_settings'%}">Drum Beat Generator</a>
</li>
</ul>

polls/templates/polls/index2.html
<br /><br />
<br />
<br />
<div class="subtitle_2nd" id="Template">Template: myproject/myapp/templates/myapp/list.html</div>

polls/templates/polls/list.html
<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <title>Minimal Django File Upload Example</title>
        </head>

        <body>
                <!-- List of uploaded documents -->
                {% if documents %}
                        <ul>
                        {% for document in documents %}
                                <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}
                                <img src="{{ document.docfile.url }}" alt="{{ document.docfile.name }}">
                                </a></li>
                        {% endfor %}
                        </ul>
                {% else %}
                        <p>No documents.</p>
                {% endif %}

                <!-- Upload form. Note enctype attribute! -->
                <form action="{% url "list" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>{{ form.non_field_errors }}</p>
                        <p>{{ form.docfile.label_tag }} </p>
                        <p>
                                {{ form.docfile.errors }}
                                {{ form.docfile }}
                        </p>
                        <p><input type="submit" value="Upload" /></p>
                </form>

        </body>

</html>

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>

<ul>
{%for choice in question.choice_set.all %}
	<li>{{choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes | pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/sheet_music.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/beats.css' %}" />